apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-geri" (include "grimnir.fullname" .) }}
  labels:
    {{- include "grimnir.labels" . | nindent 4 }}
    app.kubernetes.io/component: geri
  {{- with .Values.geri.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.geri.service.type }}
  selector:
    {{- include "grimnir.selectorLabels" (merge (dict "component" "geri") .) | nindent 4 }}
  ports:
    - name: udp-csi
      port: {{ .Values.geri.service.port }}
      targetPort: udp-csi
      protocol: UDP
    {{- if .Values.prometheus.serviceMonitor.enabled }}
    - name: metrics
      port: {{ .Values.geri.env.METRICS_PORT | int }}
      targetPort: metrics
      protocol: TCP
    {{- end }}
