{{- if and (not .Values.modelUploadAuth.existingSecret) .Values.modelUploadAuth.sharedSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grimnir.modelUploadSecretName" . }}
  labels:
    {{- include "grimnir.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.modelUploadAuth.secretKey }}: {{ .Values.modelUploadAuth.sharedSecret | quote }}
{{- end }}
