{{- if not .Values.database.existingSecret }}
{{- if not .Values.database.url }}
{{- fail "database.url is required (or provide database.existingSecret)" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-db" (include "grimnir.fullname" .) }}
  labels:
    {{- include "grimnir.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.database.secretKey }}: {{ .Values.database.url | quote }}
{{- end }}
