apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-volva" (include "grimnir.fullname" .) }}
  labels:
    {{- include "grimnir.labels" . | nindent 4 }}
    app.kubernetes.io/component: volva
  {{- with .Values.volva.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.volva.service.type }}
  selector:
    {{- include "grimnir.selectorLabels" (merge (dict "component" "volva") .) | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.volva.service.port | int }}
      targetPort: http
      protocol: TCP
